// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjtrytcayvbwdnjixwbe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqdHJ5dGNheXZid2Ruaml4d2JlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1ODExMzEsImV4cCI6MjA1NjE1NzEzMX0.jdKWjQMa2aG18aYmHgCeM-stjKGrCpKhTZZzsghw83w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);